"""
send_back_to_resolve.py
========================
Script to install in the user's Nuke (~/.nuke/). Adds a menu command
that renders the current composition and sends it back to DaVinci
Resolve, replacing the original timeline material via ReplaceClip().

INSTALLATION:
  Copy this file and resolve_nuke_bridge_common.py to ~/.nuke/, and
  add this line to menu.py:
      import send_back_to_resolve

REQUIREMENTS:
  - DaVinci Resolve Studio must be OPEN with the same project the
    clip was sent to Nuke from.
  - The .nk must have been generated by SendToNuke.py (it needs the
    bridge_metadata.json file in the same project folder).

HOW THE RESULT COMES BACK:
  ReplaceClip() updates the source file of the ORIGINAL MediaPoolItem
  directly, in place. This means: no new tracks are ever created, no
  existing tracks get shuffled around, and every instance of that
  same material anywhere in the timeline (even if it was cut into
  several pieces, or used in more than one place) updates at once,
  automatically, since they all point at the same underlying
  MediaPoolItem. This is the same behavior native "Send to Fusion"
  has in Resolve.

  The tradeoff (a deliberate choice over an earlier "place on a new
  track above the original" design) is that the original is not kept
  around for an easy side-by-side comparison: once sent back, the
  original version is gone unless you undo. If the same material
  appears elsewhere in the project, those other instances will change
  too, since ReplaceClip() affects the MediaPoolItem itself, not a
  specific timeline position.
"""

import os
import sys

import nuke

# Same robust approach as in SendToNuke.py: try a direct import
# first, and only if that fails, try the standard install location
# (~/.nuke/), without relying on __file__.
try:
    import resolve_nuke_bridge_common as bridge
except ImportError:
    _candidate_dirs = [os.path.expanduser("~/.nuke")]
    for _d in _candidate_dirs:
        if os.path.isdir(_d) and _d not in sys.path:
            sys.path.append(_d)
    import resolve_nuke_bridge_common as bridge


def _find_job_dir_for_current_script():
    """
    The .nk generated by SendToNuke.py lives inside the job folder
    (alongside bridge_metadata.json). We return that folder based on
    the location of the script currently open in Nuke.
    """
    script_path = nuke.root().name()
    if not script_path or script_path == "Root":
        return None
    return os.path.dirname(script_path)


def send_back_to_resolve():
    job_dir = _find_job_dir_for_current_script()
    if not job_dir:
        nuke.message(
            "This script does not appear to have been generated by the "
            "Resolve-Nuke bridge (the metadata folder was not found).\n\n"
            "This feature is only available for projects opened "
            "automatically from 'Send to Nuke' in Resolve."
        )
        return

    metadata = bridge.read_metadata(job_dir)
    if metadata is None:
        nuke.message(
            f"bridge_metadata.json was not found in:\n{job_dir}\n\n"
            f"Cannot determine which Resolve clip this project "
            f"corresponds to."
        )
        return

    write_node = nuke.toNode("ResolveBridge_Write1")
    if write_node is None:
        nuke.message(
            "The output node 'ResolveBridge_Write1' was not found in "
            "this project. Was it deleted or renamed by mistake?"
        )
        return

    # --- Render ---
    try:
        first = int(metadata["frame_start"])
        last = int(metadata["frame_end"])
        nuke.execute(write_node, first, last)
    except Exception as e:
        nuke.message(f"Error while rendering:\n\n{type(e).__name__}: {e}")
        return

    output_dir = metadata.get("nuke_output_dir")
    rendered_files = sorted(
        f for f in os.listdir(output_dir) if f.lower().endswith(".exr")
    ) if output_dir and os.path.isdir(output_dir) else []

    if not rendered_files:
        nuke.message(
            f"The render appeared to complete but no EXR files were "
            f"found in:\n{output_dir}\n\n"
            f"Check Nuke's console in case there were errors during "
            f"the render."
        )
        return

    # --- Connect to Resolve and locate the original MediaPoolItem ---
    resolve = bridge.get_resolve_app()
    if resolve is None:
        nuke.message(
            "Could not connect to DaVinci Resolve.\n\n"
            "The render completed successfully and is saved at:\n"
            f"{output_dir}\n\n"
            "But it could not be sent back automatically. Check that "
            "Resolve Studio is open with the same project, and try "
            "again, or import the render manually."
        )
        return

    project_manager = resolve.GetProjectManager()
    project = project_manager.GetCurrentProject() if project_manager else None
    if project is None:
        nuke.message(
            "Resolve is open but no project is loaded.\n\n"
            f"The render is ready at:\n{output_dir}\n"
            "Import it manually once you have the right project open."
        )
        return

    unique_id = metadata.get("media_pool_item_id")
    media_pool_item = bridge.find_media_pool_item_by_id(project, unique_id)
    if media_pool_item is None:
        nuke.message(
            "The original clip associated with this composition was not "
            "found in this Resolve project (the Resolve project may "
            "have changed since the clip was sent to Nuke).\n\n"
            f"The render is ready at:\n{output_dir}\n"
            "Import it manually into the Media Pool if you need it."
        )
        return

    first_rendered = os.path.join(output_dir, rendered_files[0])

    try:
        success = media_pool_item.ReplaceClip(first_rendered)
    except Exception as e:
        nuke.message(f"Error calling ReplaceClip in Resolve:\n\n{type(e).__name__}: {e}")
        return

    if success:
        nuke.message(
            f"Render successfully sent back to Resolve.\n\n"
            f"Updated clip: {metadata.get('clip_name', '?')}\n\n"
            f"Remember: this updates EVERY instance of that material "
            f"in the Resolve project, not just the one that was sent "
            f"to Nuke."
        )
    else:
        nuke.message(
            "Resolve rejected the clip update (ReplaceClip "
            "returned False).\n\n"
            f"The render is ready at:\n{output_dir}\n"
            "You can try importing it manually."
        )


# --- Menu command registration ---
nuke.menu("Nuke").addCommand(
    "Render/Send back to Resolve",
    send_back_to_resolve,
    "ctrl+alt+r"
)
